name: Cybershield Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'cybershield-backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cybershield-backend/**'

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r cybershield-backend/requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=cybershield-backend/src --cov-report=xml --cov-report=term-missing cybershield-backend/tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./cybershield-backend
          fail_ci_if_error: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cybershield-backend
          push: true
          tags: moatazq24/cybershield-backend:latest


